// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID          int64
	Title       string
	Description string
	ImageUrl    string
	Price       string
	TelegramID  int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Availability struct {
	TelegramID int64
	Weekday    int16
	StartTime  pgtype.Time
	EndTime    pgtype.Time
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Booking struct {
	ID                 int64
	StartTime          pgtype.Timestamp
	EndTime            pgtype.Timestamp
	Email              string
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
	MasterTelegramID   int64
	CustomerTelegramID int64
	AppointmentID      int64
}

type User struct {
	ID                    int64
	TelegramID            int64
	Username              string
	FirstName             string
	LastName              string
	PhotoUrl              pgtype.Text
	LanguageCode          pgtype.Text
	IsBot                 pgtype.Bool
	AllowsWriteToPm       pgtype.Bool
	AddedToAttachmentMenu pgtype.Bool
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}
